### ISSUE TITLE
Issues with latest Canary: Version 84.0.4144.2 (Build oficial) canary (64 bits)..

### ISSUE THREAD

**Issue by oscarbg** [toji/webgpu-test#1]
I'm on Nvidia Titan V with latest drivers..
maybe some updates to WebGPU IDL been done since March that require updated demo?
thanks..

**Comment by midnight-dev** [comment]
@oscarbg What exactly _are_ the issues you're now experiencing? 

Straight up crashing in Chrome Canary? Visual artifacts? Texture, geometry, lighting corruption? Waffles without syrup?

**Comment by toji** [comment]
There _have_ been some IDL changes since then, and I just did a quick pass over the code to fix the majority of the warnings I was seeing, but all of the changes were showing as deprecated but not yet removed. The page is generally still working for me, what exactly is the behavior you're seeing?

> Waffles without syrup?

I should hope not! This is a respectable repo sir-and-or-madam! We will abide no such villiany here!

**Comment by oscarbg** [comment]
Hi @toji,
some update, was not an issue of your project, but an incompatibility with an extra Chrome flag which I had enabled for a long time, with no problems running early WebGPU samples (like 
https://austineng.github.io/webgpu-samples/#twoCubes).
In fact I had used as an additional argument :
"--use-angle=gl" to "C:\Users\rtfss\AppData\Local\Google\Chrome SxS\Application\chrome.exe"
jointly with #enable-webgl2-compute-context, a leftover from testing WebGL compute..

so WebGL report site (https://webglreport.com/) reported:

Unmasked Renderer: ANGLE (NVIDIA Corporation, TITAN V/PCIe/SSE2, OpenGL 4.5 core)
ANGLE:  No

not using "--use-angle=gl" all goes back to normal, your WebGPU sample works..

now reports:
Unmasked Renderer: | ANGLE (NVIDIA TITAN V Direct3D11 vs_5_0 ps_5_0)
ANGLE: Yes, D3D9

so question is:
seems a bug, we can't have working simultaneously both WebGPU and WebGL compute..
as said earlier versions had no problem having enabled both WebGPU and Webgl Compute..

as said removing "--use-angle=gl" fixed it, but maybe it isn't needed to remove this flag and maybe an incompatibilty with other experimental flags enabled like:
#enable-webgl2-compute-context
#enable-skia-renderer
#enable-force-dark
#enable-webgl-draft-extensions

Sorry for confusion and large response :-(

will close issue anyway..

**Comment by midnight-dev** [comment]
@oscarbg That's really good documentation. Big thanks for cataloging the info so neatly. 

I'm going to have to check my extensions for Firefox. I think I had ANGLE and draft extensions enabled on at least one of my installations. I also need to remember this for future WebGPU application development.👌
